### ISSUE TITLE
Missing fixes from release 1.3.2

### ISSUE THREAD

**Issue by marcmatta** [Cocoanetics/BarCodeKit#8]
Hi @odrobnik ,
It seems that the latest release does not include all the fixes as available in the develop branch and as stated in the release notes of 1.3.2

> Version 1.3.2
> 
> @odrobnik odrobnik released this on Jun 7, 2018
> 
> FIXED: Podspec didn't specify that pod is iOS compatible
> FIXED: Some 9.4 warnings
> FIXED: The option to suppress quiet zones caused barcodes to be shifted out of the center of the generated images.
> CHANGED: Option to suppress quiet zones renamed to BCKCodeDrawingSuppressQuietZones
> 
> Announcement: https://www.cocoanetics.com/2018/06/barcodekit-1-3-2/

Can you please create a new release using Cocoapods as well?

Thanks!

**Comment by odrobnik** [comment]
Thank you for noticing and reporting! I made a fresh release: https://www.cocoanetics.com/2021/05/barcodekit-1-3-3/
